CREATE TABLE IF NOT EXISTS pets (
    id bigserial PRIMARY KEY,
    user_id BIGINT NOT NULL,
    additional_id BIGINT NOT NULL,
    pet_name VARCHAR(255) NOT NULL,
    gender VARCHAR(255) NOT NULL,
    date_of_birth DATE NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)