DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS pets;
DROP TABLE IF EXISTS specialties;
DROP TABLE IF EXISTS doctor;
DROP TABLE IF EXISTS categories;
DROP TABLE IF EXISTS booking;
DROP TABLE IF EXISTS additionals;