CREATE TABLE IF NOT EXISTS doctor (
    id bigserial PRIMARY KEY,
    specialties_id BIGINT NOT NULL,
    name VARCHAR(255) NOT NULL,
    rating DECIMAL(2, 1) NOT NULL,
    reviews INTEGER NOT NULL,
    experience INTEGER NOT NULL,
    price INTEGER NOT NULL,
    address VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)